name: oracle
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeidfvq6yso3dpxgglq7fvviy42xjf3s7bn5thmi7ogv2j6pag3rene
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeiafmboaybe3dsoo2e4cilf3m334c5dhpjws54pbwqnm5ksnrkctrq
number_of_agents: 4
deployment:
  agent:
    ports:
      0:
        8000: 8000
      1:
        8001: 8000
      2:
        8002: 8000
      3:
        8003: 8000
---
public_id: valory/oracle_abci:0.1.0
type: skill
0:
  models:
    price_api:
      args:
        url: ${PRICE_API_URL_0:str:https://api.coingecko.com/api/v3/simple/price}
        api_id: ${PRICE_API_ID_0:str:coingecko}
        parameters:
          ids: ${PRICE_API_IDS_0:str:bitcoin}
          vs_currencies: ${PRICE_API_VS_CURRENCIES_0:str:usd}
        response_key: ${PRICE_API_RESPONSE_KEY_0:str:bitcoin:usd}
        headers: {}
    randomness_api:
      args:
        url: ${RANDOMNESS_API_URL_0:str:https://drand.cloudflare.com/public/latest}
        api_id: ${RANDOMNESS_API_ID_0:str:cloudflare}
    params:
      args:
        gas_params: &id001
          gas_price: ${GAS_PRICE:int:null}
          max_fee_per_gas: ${MAX_FEE_PER_GAS:int:null}
          max_priority_fee_per_gas: ${MAX_PRIORITY_FEE_PER_GAS:int:null}
        setup: &id002
          all_participants: ${ALL_PARTICIPANTS:list:["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
            "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC", "0x90F79bf6EB2c4f870365E785982E1f101E93b906"]}
          safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x77b783e911F4398D75908Cc60C7138Bd1eFe35Fd}
          oracle_contract_address: ${ORACLE_CONTRACT_ADDRESS:str:null}
          consensus_threshold: ${CONSENSUS_THRESHOLD:int:null}
        max_healthcheck: ${MAX_HEALTHCHECK:int:43200}
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:3000}
        broadcast_to_server: ${BROADCAST_TO_SERVER:bool:false}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x998abeb3E57409262aE5b751f60747921B33613E}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        use_termination: ${USE_TERMINATION:bool:false}
        use_slashing: ${USE_SLASHING:bool:false}
        slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:3}
        slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:10000000000000000}
        light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:5000000000000000}
        serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:8000000000000000}
        sleep_time: ${SLEEP_TIME:int:5}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
    server_api:
      args: &id003
        url: ${SERVER_API:str:http://localhost:8060/deposit}
    benchmark_tool:
      args: &id004
        log_dir: ${LOG_DIR:str:/benchmarks}
1:
  models:
    price_api:
      args:
        url: ${PRICE_API_URL_1:str:https://api.kraken.com/0/public/Ticker}
        api_id: ${PRICE_API_ID_1:str:kraken}
        parameters:
          pair: ${PRICE_API_PAIR_1:str:BTCUSD}
        response_key: ${PRICE_API_RESPONSE_KEY_1:str:result:XXBTZUSD:b}
        response_index: ${PRICE_API_RESPONSE_INDEX_1:int:0}
        headers: {}
    randomness_api:
      args:
        url: ${RANDOMNESS_API_URL_1:str:https://api.drand.sh/public/latest}
        api_id: ${RANDOMNESS_API_ID_1:str:protocollabs1}
    params:
      args:
        gas_params: *id001
        setup: *id002
        max_healthcheck: ${MAX_HEALTHCHECK:int:43200}
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_1:str:node1:26666}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:3000}
        broadcast_to_server: ${BROADCAST_TO_SERVER:bool:false}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x998abeb3E57409262aE5b751f60747921B33613E}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        use_termination: ${USE_TERMINATION:bool:false}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
        use_slashing: ${USE_SLASHING:bool:false}
        slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:3}
        slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:10000000000000000}
        light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:5000000000000000}
        serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:8000000000000000}
        sleep_time: ${SLEEP_TIME:int:5}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
    server_api:
      args: *id003
    benchmark_tool:
      args: *id004
2:
  models:
    price_api:
      args:
        url: ${PRICE_API_URL_2:str:https://api.coinbase.com/v2/prices/BTC-USD/buy}
        api_id: ${PRICE_API_ID_2:str:coinbase}
        response_key: ${PRICE_API_RESPONSE_KEY_2:str:data:amount}
        headers: {}
        parameters: {}
    randomness_api:
      args:
        url: ${RANDOMNESS_API_URL_2:str:https://api2.drand.sh/public/latest}
        api_id: ${RANDOMNESS_API_ID_2:str:protocollabs2}
    params:
      args:
        gas_params: *id001
        setup: *id002
        max_healthcheck: ${MAX_HEALTHCHECK:int:43200}
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_2:str:node2:26676}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:3000}
        broadcast_to_server: ${BROADCAST_TO_SERVER:bool:false}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x998abeb3E57409262aE5b751f60747921B33613E}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        use_termination: ${USE_TERMINATION:bool:false}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
        use_slashing: ${USE_SLASHING:bool:false}
        slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:3}
        slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:10000000000000000}
        light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:5000000000000000}
        serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:8000000000000000}
        sleep_time: ${SLEEP_TIME:int:5}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
    server_api:
      args: *id003
    benchmark_tool:
      args: *id004
3:
  models:
    price_api:
      args:
        url: ${PRICE_API_URL_3:str:https://api.binance.com/api/v3/ticker/price}
        api_id: ${PRICE_API_ID_3:str:binance}
        parameters:
          symbol: ${PRICE_API_SYMBOL_3:str:BTCUSDT}
        response_key: ${PRICE_API_RESPONSE_KEY_3:str:price}
        headers: {}
    randomness_api:
      args:
        url: ${RANDOMNESS_API_URL_3:str:https://api3.drand.sh/public/latest}
        api_id: ${RANDOMNESS_API_ID_3:str:protocollabs3}
    params:
      args:
        gas_params: *id001
        setup: *id002
        max_healthcheck: ${MAX_HEALTHCHECK:int:43200}
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_3:str:node3:26686}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:3000}
        broadcast_to_server: ${BROADCAST_TO_SERVER:bool:false}
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x998abeb3E57409262aE5b751f60747921B33613E}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        validate_timeout: ${VALIDATE_TIMEOUT:int:1205}
        use_termination: ${USE_TERMINATION:bool:false}
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://dummy_service.autonolas.tech/}
        use_slashing: ${USE_SLASHING:bool:false}
        slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:3}
        slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:10000000000000000}
        light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:5000000000000000}
        serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:8000000000000000}
        sleep_time: ${SLEEP_TIME:int:5}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:0}
    server_api:
      args: *id003
    benchmark_tool:
      args: *id004
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_RPC_0:str:http://hardhat:8545}
        chain_id: ${CHAIN_ID:int:31337}
        poa_chain: ${POA_CHAIN:bool:false}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_RPC_1:str:http://hardhat:8545}
        chain_id: ${CHAIN_ID:int:31337}
        poa_chain: ${POA_CHAIN:bool:false}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_RPC_2:str:http://hardhat:8545}
        chain_id: ${CHAIN_ID:int:31337}
        poa_chain: ${POA_CHAIN:bool:false}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_RPC_3:str:http://hardhat:8545}
        chain_id: ${CHAIN_ID:int:31337}
        poa_chain: ${POA_CHAIN:bool:false}
        default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
