name: oracle_ropsten
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeifpb54id7wln2ayku65s3qmih3aljf23rfpsggjwuzc7cnkfroi7y
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeifesfjjlhqglhh7bn7tuhifbdqwsmn37avlthm25kam2oow3wk6eq
number_of_agents: 4
---
extra:
  setup_args:
    args: &id001
      setup:
        safe_contract_address:
        - '0x7AbCC2424811c342BC9A9B52B1621385d7406676'
        oracle_contract_address:
        - '0xB555E44648F6Ff759F64A5B451AB845B0450EA57'
      max_healthcheck: 43200
      broadcast_to_server: false
  valory_monitoring_backend:
    args: &id002
      url: https://oracle-server.staging.autonolas.tech/deposit
public_id: valory/oracle_abci:0.1.0
type: skill
0:
  models:
    price_api:
      args:
        url: https://api.coingecko.com/api/v3/simple/price
        api_id: coingecko
        parameters:
          ids: bitcoin
          vs_currencies: usd
        response_key: bitcoin:usd
        headers: {}
    randomness_api:
      args:
        url: https://drand.cloudflare.com/public/latest
        api_id: cloudflare
    params:
      args: *id001
    server_api:
      args: *id002
1:
  models:
    price_api:
      args:
        url: https://api.kraken.com/0/public/Ticker
        api_id: kraken
        parameters:
          pair: BTCUSD
        response_key: result:XXBTZUSD:b
        response_index: 0
    randomness_api:
      args:
        url: https://api.drand.sh/public/latest
        api_id: protocollabs1
    params:
      args: *id001
    server_api:
      args: *id002
2:
  models:
    price_api:
      args:
        url: https://api.coinbase.com/v2/prices/BTC-USD/buy
        api_id: coinbase
        response_key: data:amount
        headers: {}
        parameters: {}
    randomness_api:
      args:
        url: https://api2.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args: *id001
    server_api:
      args: *id002
3:
  models:
    price_api:
      args:
        url: https://api.binance.com/api/v3/ticker/price
        api_id: binance
        parameters:
          symbol: BTCUSDT
        response_key: price
        headers: {}
    randomness_api:
      args:
        url: https://api3.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args: *id001
    server_api:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_ROPSTEN_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 3
        poa_chain: false
        default_gas_price_strategy: eip1559
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_ROPSTEN_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 3
        poa_chain: false
        default_gas_price_strategy: eip1559
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_ROPSTEN_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 3
        poa_chain: false
        default_gas_price_strategy: eip1559
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_ROPSTEN_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 3
        poa_chain: false
        default_gas_price_strategy: eip1559
