agent_name: oracle
author: valory
version: 0.1.0
license: Apache-2.0
description: Oracle agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeia6rbpcaovvels4mn3ufkbbvwrsibury3x5g6eyo4lws4w2uk3x4q
  __init__.py: bafybeieja6fkcncllqarspvtzsnm25g6ttxkxfdk2jduuozvt5a3uin6t4
  tests/__init__.py: bafybeiddkyv7ohqiylizxurzs4ihom2o5rpqbwf5xufzkz3jpa7umpwgmm
  tests/test_oracle.py: bafybeidkhguqtwdm46mwybyrsergajqfyqu262ikfqwu7vxfzsox5bli5i
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihvscddpxjbtqsetngmxo3kiht2wqhosmwiyuh3f6zjti3x3byu5u
- valory/abci:0.1.0:bafybeibiwiza4rqma5pzeoucndsibnu2pvune6cm37mpnvf5ilkrqyvg44
- valory/http_client:0.23.0:bafybeifgeqgryx6b3s6eseyzyezygmeitcpt3tkor2eiycozoi6clgdrny
- valory/ledger:0.19.0:bafybeigdckv3e6bz6kfloz4ucqrsufft6k4jp6bwkbbcvh4fxvgbmzq3dm
- valory/p2p_libp2p_client:0.1.0:bafybeihge56dn3xep2dzomu7rtvbgo4uc2qqh7ljl3fubqdi2lq44gs5lq
contracts:
- valory/gnosis_safe:0.1.0:bafybeiaiwsdkahhluledg3n4gmejht6oxi7zbfkqruxqe4yj3anbb2x7yi
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeihhph53ahspmfvblvlmpz3vmcnhnm2bzy3547k3vpezgty4xfhyvu
- valory/offchain_aggregator:0.1.0:bafybeidfqsrkqz4a2edlrw73vhrwec6rx45u257dzouym7qrxj54rz6aoi
- valory/service_registry:0.1.0:bafybeiatuyvnip3gzzc26oieudmkgdkvil3nerzbfa2j7woi4sbusgxtye
protocols:
- open_aea/signing:1.0.0:bafybeie7xyems76v5b4wc2lmaidcujizpxfzjnnwdeokmhje53g7ym25ii
- valory/abci:0.1.0:bafybeihmzlmmb4pdo3zkhg6ehuyaa4lhw7bfpclln2o2z7v3o6fcep26iu
- valory/acn:1.1.0:bafybeic2pxzfc3voxl2ejhcqyf2ehm4wm5gxvgx7bliloiqi2uppmq6weu
- valory/contract_api:1.0.0:bafybeialhbjvwiwcnqq3ysxcyemobcbie7xza66gaofcvla5njezkvhcka
- valory/http:1.0.0:bafybeiejoqgv7finfxo3rcvvovrlj5ccrbgxodjq43uo26ylpowsa3llfe
- valory/ledger_api:1.0.0:bafybeige5agrztgzfevyglf7mb4o7pzfttmq4f6zi765y4g2zvftbyowru
- valory/tendermint:0.1.0:bafybeig6g6twajlwssfbfp5rlnu5mwzuu5kgak5cs4fich7rlkx6whesnu
skills:
- valory/abstract_abci:0.1.0:bafybeih6ilyszil7opntt3tkasryghu7j2qj2m5txwoo4tsdsvkuxas7di
- valory/abstract_round_abci:0.1.0:bafybeib5d3tt3jkd5b3sr2pbf2jkogicxxywve3z7n5ebau7vz4ibfsvq4
- valory/oracle_abci:0.1.0:bafybeifmniujadn2fetejvoeph6lwlp6h26k3srucptvdspvkhugrosqei
- valory/oracle_deployment_abci:0.1.0:bafybeiadaab6r2f6r47xdpm4mxsi64zddyt7xc2n5bh4qvpnysmqziabgy
- valory/price_estimation_abci:0.1.0:bafybeibyw5glvcve3h4dveuah63qqp2qct6jeofc6qnfuugnk74doswzfq
- valory/registration_abci:0.1.0:bafybeih6armcjufwhkugsyj3vhbb77jsgavld53ragmkiayscpjmi3gesi
- valory/reset_pause_abci:0.1.0:bafybeihtcgzfacdeoi2osyd5kedm4heoxkcgtsgkhxx4t7vecyu6fj2vai
- valory/termination_abci:0.1.0:bafybeif5bcmaxms3f4mtjcke2rgdohgkhpy75ugk7ygtzv3izygy44tk6q
- valory/transaction_settlement_abci:0.1.0:bafybeialer7rwrg6k6htnlotuvxhfhwthd5pvvhnxo3ndhwqlr53htd7wy
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.41.0.post1
  open-aea-ledger-ethereum:
    version: ==1.41.0.post1
  open-aea-test-autonomy:
    version: ==0.13.3
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/oracle_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/oracle_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  price_api:
    args:
      url: ${str:https://api.coinbase.com/v2/prices/BTC-USD/buy}
      api_id: ${str:coinbase}
      parameters:
        ids: ${str:null}
        vs_currencies: ${str:null}
        pair: ${str:null}
        symbol: ${str:null}
      response_key: ${str:data:amount}
      response_index: ${int:null}
      headers: ${dict:{}}
  randomness_api:
    args:
      url: ${str:https://drand.cloudflare.com/public/latest}
      api_id: ${str:cloudflare}
  params:
    args:
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${str:null}
        oracle_contract_address: ${str:null}
        consensus_threshold: ${int:null}
      gas_params:
        gas_price: ${int:null}
        max_fee_per_gas: ${int:null}
        max_priority_fee_per_gas: ${int:null}
      round_timeout_seconds: ${float:35.0}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      reset_tendermint_after: ${int:10}
      reset_pause_duration: ${int:300}
      max_healthcheck: ${int:1200}
      multisend_address: ${str:'0x0000000000000000000000000000000000000000'}
      broadcast_to_server: ${bool:false}
      validate_timeout: ${int:1205}
      service_registry_address: ${str:null}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      share_tm_config_on_startup: ${bool:false}
      on_chain_service_id: ${int:null}
      init_fallback_gas: ${int:270000}
      use_termination: ${bool:false}
      service_endpoint_base: ${str:https://dummy_service.autonolas.tech/}
      use_slashing: ${bool:false}
      slash_cooldown_hours: ${int:3}
      slash_threshold_amount: ${int:10000000000000000}
      light_slash_unit_amount: ${int:5000000000000000}
      serious_slash_unit_amount: ${int:8000000000000000}
      sleep_time: ${int:5}
  server_api:
    args:
      url: ${str:http://192.168.2.17:9999/deposit}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: fetchai/http_server:0.22.0
type: connection
config:
  api_spec_path: ${str:null}
  host: ${str:0.0.0.0}
  port: ${int:8000}
  ssl_cert: ${str:null}
  ssl_key: ${str:null}
  target_skill_id: valory/oracle_abci:0.1.0
