agent_name: oracle
author: valory
version: 0.1.0
license: Apache-2.0
description: Oracle agent.
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: bafybeia6rbpcaovvels4mn3ufkbbvwrsibury3x5g6eyo4lws4w2uk3x4q
  __init__.py: bafybeieja6fkcncllqarspvtzsnm25g6ttxkxfdk2jduuozvt5a3uin6t4
  tests/__init__.py: bafybeiddkyv7ohqiylizxurzs4ihom2o5rpqbwf5xufzkz3jpa7umpwgmm
  tests/test_oracle.py: bafybeidkhguqtwdm46mwybyrsergajqfyqu262ikfqwu7vxfzsox5bli5i
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihaax5od5zo5jk2l62hv4jwuwtxloh5mijozudpsjombqc4ncmi6i
- valory/abci:0.1.0:bafybeih2l6ssf5ebkvgbag3hx2pd22shytszqavveib2e2s6rv4va5khv4
- valory/http_client:0.23.0:bafybeidykl4elwbcjkqn32wt5h4h7tlpeqovrcq3c5bcplt6nhpznhgczi
- valory/ledger:0.19.0:bafybeicgfupeudtmvehbwziqfxiz6ztsxr5rxzvalzvsdsspzz73o5fzfi
- valory/p2p_libp2p_client:0.1.0:bafybeidwcobzb7ut3efegoedad7jfckvt2n6prcmd4g7xnkm6hp6aafrva
contracts:
- valory/gnosis_safe:0.1.0:bafybeifvqalsuyetul3ypuolxvxzi5ffxoqdbqpfl3jadqjachsw7qfs74
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeierle6peb4a5cw3tncgondwhgesomzg7tedkb5cuos2zm462asbdi
- valory/offchain_aggregator:0.1.0:bafybeihpg6b5fypdizpclgsbzskcnu4v7fxyi75alr2ulprcm543fqhk7q
- valory/service_registry:0.1.0:bafybeiatzikdgcjteti6xeid4bvofszuavxb4fnczx33lcsvlaui4wpwua
protocols:
- open_aea/signing:1.0.0:bafybeibqlfmikg5hk4phzak6gqzhpkt6akckx7xppbp53mvwt6r73h7tk4
- valory/abci:0.1.0:bafybeig3dj5jhsowlvg3t73kgobf6xn4nka7rkttakdb2gwsg5bp7rt7q4
- valory/acn:1.1.0:bafybeignmc5uh3vgpuckljcj2tgg7hdqyytkm6m5b6v6mxtazdcvubibva
- valory/contract_api:1.0.0:bafybeidv6wxpjyb2sdyibnmmum45et4zcla6tl63bnol6ztyoqvpl4spmy
- valory/http:1.0.0:bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty
- valory/ledger_api:1.0.0:bafybeibo4bdtcrxi2suyzldwoetjar6pqfzm6vt5xal22ravkkcvdmtksi
- valory/tendermint:0.1.0:bafybeicusvezoqlmyt6iqomcbwaz3xkhk2qf3d56q5zprmj3xdxfy64k54
skills:
- valory/abstract_abci:0.1.0:bafybeifuclb6cikagtg2zn7dkjnnv3f7re2tfgzk6c4h3scgyzaaqeg55m
- valory/abstract_round_abci:0.1.0:bafybeigiolzp3i6b3wwuau3yv2h5udqape3i7of73mlm2d6ud22irlkbme
- valory/oracle_abci:0.1.0:bafybeibkq4mqmpziwdqb232qyda3f4s3zeklblxfus7thp5w6pe7oq4hi4
- valory/oracle_deployment_abci:0.1.0:bafybeifshvbncgjd7rzzf2br65t5uwkh5g5c5xsoh2sdqthtnzso5oxddm
- valory/price_estimation_abci:0.1.0:bafybeibytrfkejdri6vq66652trd74uwxkfj37mq4rfbjnx4ov7kaucf6y
- valory/registration_abci:0.1.0:bafybeigjzfdhhu6ody2qo5v2xjobafujnodklia4zw6bkkhahxtjfo3wby
- valory/reset_pause_abci:0.1.0:bafybeieeux3rdlcwgjbdfrluvkhqv26qdparre6pabatietw7juklljil4
- valory/termination_abci:0.1.0:bafybeifkl4ab6dnvtsaefe56dbzshmp5mozn7exwcaj2a3wjeq7u3hpezm
- valory/transaction_settlement_abci:0.1.0:bafybeifsz2ll7gmy6vmx34t6q5bdv6zzwp5zrehr6di6v3thcpc3sztkta
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: ${LOG_LEVEL:str:INFO}
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: true
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.32.0
  open-aea-ledger-ethereum:
    version: ==1.32.0
  open-aea-test-autonomy:
    version: ==0.10.2
skill_exception_policy: stop_and_exit
connection_exception_policy: just_log
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/oracle_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2024-01-01'
  not_before: '2023-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_9005.txt
---
public_id: valory/oracle_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: ${str:/benchmarks}
  price_api:
    args:
      url: ${str:https://api.coinbase.com/v2/prices/BTC-USD/buy}
      api_id: ${str:coinbase}
      parameters:
        ids: ${str:null}
        vs_currencies: ${str:null}
        pair: ${str:null}
        symbol: ${str:null}
      response_key: ${str:data:amount}
      response_index: ${int:null}
      headers: ${dict:{}}
  randomness_api:
    args:
      url: ${str:https://drand.cloudflare.com/public/latest}
      api_id: ${str:cloudflare}
  params:
    args:
      setup:
        all_participants: ${list:[]}
        safe_contract_address: ${str:null}
        oracle_contract_address: ${str:null}
        consensus_threshold: ${int:null}
      round_timeout_seconds: ${float:35.0}
      tendermint_url: ${str:http://localhost:26657}
      tendermint_com_url: ${str:http://localhost:8080}
      reset_tendermint_after: ${int:10}
      reset_pause_duration: ${int:300}
      max_healthcheck: ${int:1200}
      multisend_address: ${str:'0x0000000000000000000000000000000000000000'}
      broadcast_to_server: ${bool:false}
      validate_timeout: ${int:1205}
      service_registry_address: ${str:null}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      share_tm_config_on_startup: ${bool:false}
      on_chain_service_id: ${int:null}
      init_fallback_gas: ${int:270000}
      use_termination: ${bool:false}
  server_api:
    args:
      url: ${str:http://192.168.2.17:9999/deposit}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:31337}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: fetchai/http_server:0.22.0
type: connection
config:
  api_spec_path: null
  host: 0.0.0.0
  port: 8000
  ssl_cert: null
  ssl_key: null
  target_skill_id: valory/oracle_abci:0.1.0
