name: oracle_polygon
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeifqnvekc6s44wsczofdhofiozxekstjau2bk5yqfqvjuv4wzoopku
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeihotaqdccezgn7cxdxydubechcuudhdhhhd2auogfq4mmr5whvkqa
number_of_agents: 4
---
extra:
  params_args:
    args: &id001
      setup:
        all_participants:
        - - '0xe6b7e278a184b1183f743380D9Ef12167cDe37c6'
          - '0x4b23D773D0e9469d1f92DC8B0eC8A8B19Cfa1771'
          - '0xAD56A50628D4915E841b7C2eCE13b33793b365d0'
          - '0x5eF6567079c6c26d8ebf61AC0716163367E9B3cf'
        safe_contract_address:
        - '0x37ba5291A5bE8cbE44717a0673fe2c5a45B4B6A8'
        oracle_contract_address:
        - '0x3d9e92B0FE7673ddA3d7C33B9ff302768A03de19'
        consensus_threshold:
        - null
      max_healthcheck: 43200
      observation_interval: 3000
      broadcast_to_server: true
      validate_timeout: 300
  valory_monitoring_backend:
    args: &id002
      url: https://oracle-server.autonolas.tech/deposit
public_id: valory/oracle_abci:0.1.0
type: skill
0:
  models:
    price_api:
      args:
        url: https://api.coingecko.com/api/v3/simple/price
        api_id: coingecko
        parameters:
          ids: bitcoin
          vs_currencies: usd
        response_key: bitcoin:usd
    randomness_api:
      args:
        url: https://drand.cloudflare.com/public/latest
        api_id: cloudflare
    params:
      args: *id001
    server_api:
      args: *id002
1:
  models:
    price_api:
      args:
        url: https://api.kraken.com/0/public/Ticker
        api_id: kraken
        parameters:
          pair: BTCUSD
        response_key: result:XXBTZUSD:b
        response_index: 0
    randomness_api:
      args:
        url: https://api.drand.sh/public/latest
        api_id: protocollabs1
    params:
      args: *id001
    server_api:
      args: *id002
2:
  models:
    price_api:
      args:
        url: https://api.coinbase.com/v2/prices/BTC-USD/buy
        api_id: coinbase
        response_key: data:amount
    randomness_api:
      args:
        url: https://api2.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args: *id001
    server_api:
      args: *id002
3:
  models:
    price_api:
      args:
        url: https://api.binance.com/api/v3/ticker/price
        api_id: binance
        parameters:
          symbol: BTCUSDT
        response_key: price
    randomness_api:
      args:
        url: https://api3.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args: *id001
    server_api:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_POLYGON_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 137
        poa_chain: true
        default_gas_price_strategy: eip1559_polygon
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_POLYGON_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 137
        poa_chain: true
        default_gas_price_strategy: eip1559_polygon
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_POLYGON_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 137
        poa_chain: true
        default_gas_price_strategy: eip1559_polygon
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_POLYGON_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 137
        poa_chain: true
        default_gas_price_strategy: eip1559_polygon
