name: oracle_hardhat
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeieqpbuzrxtfo5hz3gsb64aumnfbxad4tpxp4s46jxj7byb3zxx34y
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeidrzudseyohwzz42pwuqruap3wajt7yzzyexyp454mvgg5ihez4ae
number_of_agents: 4
---
extra:
  setup_args:
    args: &id001
      setup:
        all_participants:
        - - '0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65'
          - '0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc'
          - '0x976EA74026E726554dB657fA54763abd0C3a0aa9'
          - '0x14dC79964da2C08b23698B3D3cc7Ca32193d9955'
        safe_contract_address:
        - '0xD8dE647170163a981bb3Fdb2063583eAcF7D55AC'
        oracle_contract_address: []
      observation_interval: 30
      broadcast_to_server: false
      service_registry_address: '0x998abeb3E57409262aE5b751f60747921B33613E'
      share_tm_config_on_startup: false
      on_chain_service_id: 1
  benchmark_persistence_params:
    args: &id002
      log_dir: /benchmarks
public_id: valory/oracle_abci:0.1.0
type: skill
0:
  models:
    price_api:
      args:
        url: https://api.coingecko.com/api/v3/simple/price
        api_id: coingecko
        parameters:
        - - ids
          - bitcoin
        - - vs_currencies
          - usd
        response_key: bitcoin:usd
        headers: []
    randomness_api:
      args:
        url: https://drand.cloudflare.com/public/latest
        api_id: cloudflare
    params:
      args: *id001
    benchmark_tool:
      args: *id002
1:
  models:
    price_api:
      args:
        url: https://api.kraken.com/0/public/Ticker
        api_id: kraken
        parameters:
        - - pair
          - BTCUSD
        response_key: result:XXBTZUSD:b
        response_index: 0
    randomness_api:
      args:
        url: https://api.drand.sh/public/latest
        api_id: protocollabs1
    params:
      args: *id001
    benchmark_tool:
      args: *id002
2:
  models:
    price_api:
      args:
        url: https://api.coinbase.com/v2/prices/BTC-USD/buy
        api_id: coinbase
        response_key: data:amount
        headers: []
        parameters: []
    randomness_api:
      args:
        url: https://api2.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args: *id001
    benchmark_tool:
      args: *id002
3:
  models:
    price_api:
      args:
        url: https://api.binance.com/api/v3/ticker/price
        api_id: binance
        parameters:
        - - symbol
          - BTCUSDT
        response_key: price
        headers: []
    randomness_api:
      args:
        url: https://api3.drand.sh/public/latest
        api_id: protocollabs3
    params:
      args: *id001
    benchmark_tool:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_ORACLE_HARDHAT_RPC:str:http://host.docker.internal:8545}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559
