name: oracle_goerli
author: valory
version: 0.1.0
description: A set of agents implementing a price oracle
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeig4wu7inb6ibwfgged3djyc7emopcg5n7d7gwrlotne53pp3jfgq4
fingerprint_ignore_patterns: []
agent: valory/oracle:0.1.0:bafybeigcdlxrtwt5xgao5tlsrudizso4nvjrgk4veejrncd3osob6sjeym
number_of_agents: 4
---
extra:
  params_args:
    args:
      setup: &id001
        safe_contract_address:
        - '0x623cE6087190B53520f00609d41d79e5B71B881F'
        oracle_contract_address:
        - '0xA2b06beb69b5e454759976ABa7555e2639c0522f'
      max_healthcheck: 43200
      observation_interval: 3000
      broadcast_to_server: true
  valory_monitoring_backend:
    args: &id002
      url: https://oracle-server.staging.autonolas.tech/deposit
public_id: valory/oracle_abci:0.1.0
type: skill
0:
  models:
    price_api:
      args:
        url: https://api.coingecko.com/api/v3/simple/price
        api_id: coingecko
        parameters:
        - - ids
          - bitcoin
        - - vs_currencies
          - usd
        response_key: bitcoin:usd
        headers: null
    randomness_api:
      args:
        url: https://drand.cloudflare.com/public/latest
        api_id: cloudflare
    params:
      args:
        setup: *id001
        max_healthcheck: 43200
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_0:str:node0:26656}
        observation_interval: 3000
        broadcast_to_server: true
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:none}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
    server_api:
      args: *id002
1:
  models:
    price_api:
      args:
        url: https://api.kraken.com/0/public/Ticker
        api_id: kraken
        parameters:
        - - pair
          - BTCUSD
        response_key: result:XXBTZUSD:b
        response_index: 0
    randomness_api:
      args:
        url: https://api.drand.sh/public/latest
        api_id: protocollabs1
    params:
      args:
        setup: *id001
        max_healthcheck: 43200
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_1:str:node1:26666}
        observation_interval: 3000
        broadcast_to_server: true
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:none}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
    server_api:
      args: *id002
2:
  models:
    price_api:
      args:
        url: https://api.coinbase.com/v2/prices/BTC-USD/buy
        api_id: coinbase
        response_key: data:amount
        headers: null
        parameters: null
    randomness_api:
      args:
        url: https://api2.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args:
        setup: *id001
        max_healthcheck: 43200
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_2:str:node2:26676}
        observation_interval: 3000
        broadcast_to_server: true
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:none}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
    server_api:
      args: *id002
3:
  models:
    price_api:
      args:
        url: https://api.binance.com/api/v3/ticker/price
        api_id: binance
        parameters:
        - - symbol
          - BTCUSDT
        response_key: price
        headers: null
    randomness_api:
      args:
        url: https://api3.drand.sh/public/latest
        api_id: protocollabs2
    params:
      args:
        setup: *id001
        max_healthcheck: 43200
        tendermint_p2p_url: ${TM_P2P_ENDPOINT_NODE_3:str:node3:26686}
        observation_interval: 3000
        broadcast_to_server: true
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:none}
        service_registry_address: '0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a'
    server_api:
      args: *id002
---
public_id: valory/ledger:0.19.0
type: connection
0:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_GOERLI_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 5
        poa_chain: true
        default_gas_price_strategy: eip1559
1:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_GOERLI_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 5
        poa_chain: true
        default_gas_price_strategy: eip1559
2:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_GOERLI_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 5
        poa_chain: true
        default_gas_price_strategy: eip1559
3:
  config:
    ledger_apis:
      ethereum:
        address: ${SERVICE_ORACLE_GOERLI_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 5
        poa_chain: true
        default_gas_price_strategy: eip1559
